# Generated by Django 4.1.6 on 2023-02-20 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_personas', '0003_formulario_persona_formulario_pld_formulario_trabajo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_domicilio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del banco')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='CatalogoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=30, verbose_name='Cuenta contable')),
                ('cuentaSiti', models.CharField(max_length=15, verbose_name='Cuenta Siti')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre cuenta')),
                ('clasificacion', models.CharField(choices=[('C', 'Capitulo'), ('S', 'Subn Capitulo'), ('M', 'Mayor'), ('E', 'Menor')], default='C', max_length=1, verbose_name='Clasificación contable')),
                ('grupo', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('C', 'Capital'), ('R', 'Resultado Acreedor'), ('D', 'Resultado Deudor'), ('O', 'Orden'), ('U', 'Puente')], default='A', max_length=1, verbose_name='Grupo contable')),
                ('finalidad', models.CharField(choices=[('C', 'Caja'), ('B', 'Banco'), ('O', 'Otros')], default='O', max_length=1, verbose_name='Finalidad contable')),
                ('naturaleza', models.CharField(choices=[('A', 'Deudora'), ('D', 'Acreedora')], default='A', max_length=1, verbose_name='Naturaleza contable')),
                ('afectable', models.BooleanField(default=0, verbose_name='Afectable')),
                ('padre', models.CharField(max_length=30, verbose_name='Padre o nivel superior de la cuenta')),
                ('nivel', models.IntegerField()),
                ('balance', models.BooleanField(default=0, verbose_name='La cuenta se desplegara en el balance')),
                ('catalogoMinimo', models.BooleanField(default=0, verbose_name='Desplegar en el catalogo Minimo')),
                ('nombreBalance', models.CharField(max_length=100, verbose_name='Nombre que desplegara en el balance')),
                ('nombreSiti', models.CharField(max_length=70, verbose_name='Nombre de la cuenta en el SITI')),
                ('cuentaPadreSiti', models.CharField(max_length=15, verbose_name='Padre o nivel superior cuenta SITI')),
                ('cuentaAgrupar', models.CharField(max_length=30, verbose_name='Cuenta a la que agrupará')),
                ('ordenSiti', models.IntegerField(verbose_name='Orden en que desplegara en la base del SITI')),
                ('subCuentaSiti', models.BooleanField(verbose_name='SubCuenta de catalogo SITI')),
                ('prorrateo', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Catalogo de cuenta',
                'verbose_name_plural': 'Catalogo de cuentas',
            },
        ),
        migrations.CreateModel(
            name='ClaveUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=8)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Clave Unidad',
                'verbose_name_plural': 'Claves Unidad',
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Egreso'), ('I', 'Ingreso'), ('D', 'Diario')], max_length=1, verbose_name='Tipo de poliza')),
                ('numero', models.IntegerField(verbose_name='Número de poliza')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de poliza')),
                ('fecharegistro', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto de la poliza')),
                ('usuarioElabora', models.IntegerField(verbose_name='Usuario Elabora:')),
                ('aplicacion', models.CharField(choices=[('N', 'Normal'), ('C', 'Condonacion'), ('O', 'ChequeOrden'), ('D', 'CierreDiario'), ('M', 'CierreMensual'), ('A', 'CierreAnual')], default='N', max_length=1, verbose_name='Aplicacion de poliza')),
                ('fuente', models.CharField(choices=[('O', 'Operacion'), ('A', 'Activos'), ('N', 'Nomina'), ('G', 'Gastos'), ('P', 'Pasiva'), ('T', 'Traslados'), ('R', 'Traspasos')], default='O', max_length=1, verbose_name='Fuente de poliza')),
                ('automatica', models.BooleanField(verbose_name='Poliza automatica')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_personas.sucursal', verbose_name='Sucursal a la que pertenece:')),
                ('usuarioAutoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Autoriza:')),
            ],
            options={
                'verbose_name': 'Poliza',
                'verbose_name_plural': 'Polizas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del proveedor')),
                ('rfc', models.CharField(max_length=15, unique=True, verbose_name='RFC')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('telefono', models.CharField(max_length=10, verbose_name='Número de teléfono')),
                ('tipo', models.CharField(choices=[('N', '04 Nacional'), ('E', '05 Extranjera'), ('G', '15 Glonbal')], default='N', max_length=1, verbose_name='Tipo de proveedor')),
                ('operacion', models.CharField(choices=[('P', '03 Por servicios profesionales'), ('A', '06 Arrendamiento'), ('O', '85 Otros')], default='P', max_length=1, verbose_name='Operacion de proveedor')),
                ('regimen', models.CharField(max_length=100, verbose_name='Regimen Fiscal')),
                ('nombreExtranjero', models.CharField(max_length=50)),
                ('paisResidencia', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('cuentaClabe', models.CharField(max_length=25)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_polizas.banco')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_domicilio.domicilio')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='PolizaSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastoacomprobar', models.IntegerField(default=0)),
                ('archivo', models.CharField(blank=True, max_length=300)),
                ('chavecfdi', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rfc', models.CharField(blank=True, max_length=15)),
                ('polizaSoporteRelacion', models.IntegerField(default=0)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_polizas.poliza')),
            ],
            options={
                'verbose_name': 'PolizaSoporte',
                'verbose_name_plural': 'PolizasSoporte',
            },
        ),
        migrations.CreateModel(
            name='PolizaEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario', models.CharField(max_length=70, verbose_name='Nombre del beneficiario')),
                ('cheque', models.CharField(max_length=10, verbose_name='Numero de cheque')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_polizas.banco')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_polizas.poliza')),
            ],
            options={
                'verbose_name': 'Poliza Egreso',
                'verbose_name_plural': 'Polizas Egreso',
            },
        ),
        migrations.CreateModel(
            name='DetallePolizaSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveProdServ', models.CharField(max_length=8)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=100)),
                ('unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('objetoImp', models.CharField(max_length=2)),
                ('base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.CharField(max_length=3)),
                ('tipoFactor', models.CharField(max_length=20)),
                ('tasaoCuota', models.DecimalField(decimal_places=6, max_digits=8)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('claveUnidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_polizas.claveunidad')),
                ('polizaSoporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_polizas.polizasoporte')),
            ],
            options={
                'verbose_name': 'Detalle Poliza Soporte',
                'verbose_name_plural': 'Detalle Polizas Soporte',
            },
        ),
        migrations.CreateModel(
            name='DetallePoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('abono', models.DecimalField(decimal_places=2, max_digits=14)),
                ('concepto', models.CharField(max_length=100)),
                ('iva', models.CharField(choices=[('NA', 'No aplica'), ('16', '16%'), ('8', '8%'), ('11', '11%'), ('0', '0%'), ('E', 'Excento'), ('R', 'Retenido')], default='NA', max_length=2, verbose_name='Tasa de IVA')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_polizas.catalogocuenta')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_polizas.poliza')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_polizas.proveedor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_personas.sucursal')),
            ],
            options={
                'verbose_name': 'Detalle Poliza',
                'verbose_name_plural': 'Detalle Polizas',
            },
        ),
    ]
