# Generated by Django 4.1.6 on 2023-02-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_polizas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='tipo',
            field=models.CharField(choices=[('E', 'Egreso'), ('I', 'Ingreso'), ('D', 'Diario')], default='E', max_length=1, verbose_name='Tipo de poliza'),
        ),
    ]
