# Generated by Django 4.1.6 on 2023-02-26 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_polizas', '0004_alter_poliza_usuarioautoriza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='usuarioAutoriza',
            field=models.IntegerField(verbose_name='Usuario Elabora:'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='usuarioElabora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Autoriza:'),
        ),
    ]
