# Generated by Django 4.1.6 on 2023-02-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarraLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo:')),
                ('url', models.CharField(max_length=50, verbose_name='URL:')),
                ('orden', models.CharField(max_length=50, verbose_name='Orden:')),
                ('is_active', models.BooleanField(verbose_name='Esta activo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
