# Generated by Django 4.1.6 on 2023-02-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0003_barralinks_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barralinks',
            name='icono',
        ),
        migrations.AlterField(
            model_name='barralinks',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Principal'), (2, 'Catalogo trabajo'), (2, 'Catalogo pld')], default=1),
        ),
    ]
