# Generated by Django 4.1.6 on 2023-02-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0004_remove_barralinks_icono_alter_barralinks_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barralinks',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Principal'), (2, 'Catalogo trabajo'), (3, 'Catalogo pld')], default=1),
        ),
    ]
