# Generated by Django 4.1.6 on 2023-02-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0006_alter_barralinks_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barralinks',
            name='is_active',
        ),
        migrations.AddField(
            model_name='barralinks',
            name='solo_admin',
            field=models.BooleanField(default=True, verbose_name='Solo podran verlo el administrador'),
        ),
    ]
