# Generated by Django 4.1.6 on 2023-03-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0008_alter_barralinks_solo_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barralinks',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Acciones'), (2, 'Catalogo trabajo'), (3, 'Catalogo pld'), (4, 'Catalogo personas'), (5, 'Catalogo formularios'), (6, 'Catalogo domicilo'), (7, 'Catalogo polizas')], default=1),
        ),
    ]
