# Generated by Django 4.1.6 on 2023-02-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre de la calle')),
                ('tipo', models.CharField(choices=[('C', 'Calle'), ('A', 'Avenida'), ('P', 'Prolongación'), ('E', 'Cerrada'), ('R', 'Privada'), ('L', 'Calzada'), ('O', 'Otro')], max_length=1)),
            ],
            options={
                'verbose_name': 'Calle',
                'verbose_name_plural': 'Calles',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=5, verbose_name='CP:')),
                ('colonia', models.CharField(max_length=50, verbose_name='Barrio/Colonia')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero exterior')),
                ('interior', models.CharField(max_length=10, verbose_name='Interior')),
                ('geolocalizacion', models.CharField(max_length=50, verbose_name='Geo localizacion')),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calle', to='app_domicilio.calle', verbose_name='Calle')),
                ('entrecalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrecalle', to='app_domicilio.calle', verbose_name='Entre la Calle')),
                ('ycalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ycalle', to='app_domicilio.calle', verbose_name='Y la Calle')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
    ]
