# Generated by Django 4.1.5 on 2023-01-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_PLD', '0001_initial'),
        ('app_domicilio', '0001_initial'),
        ('app_personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('empleosFijos', models.IntegerField()),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_domicilio.domicilio')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dias', models.IntegerField()),
                ('meses', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Frecuencia',
                'verbose_name_plural': 'Frecuencias',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTrabajo', models.DateField(auto_now_add=True, null=True)),
                ('arraigoLaboralAnterior', models.CharField(max_length=100)),
                ('igresoOrdinario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('otrosIngresos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('conceptoIngresos', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10, verbose_name='Número de Teléfono del trabajo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_trabajo.empresa')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_personas.persona')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_trabajo.puesto')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP:')),
                ('rfc', models.CharField(max_length=15, verbose_name='RFC:')),
                ('Identificacion', models.CharField(choices=[('I', 'INE'), ('C', 'Cartilla'), ('P', 'Pasaporte'), ('O', 'Otros'), ('N', 'No Aplica')], max_length=1)),
                ('NumeroIdentificacion', models.CharField(max_length=30, verbose_name='Número de identificación:')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:')),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_domicilio.domicilio')),
                ('persona', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_personas.persona')),
                ('pld', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_PLD.pld')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='frecuencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_trabajo.frecuencia'),
        ),
    ]
