# Generated by Django 4.1.6 on 2023-02-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_trabajo', '0001_initial'),
        ('app_personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_trabajo.socio'),
        ),
    ]
