# Generated by Django 4.1.6 on 2023-02-05 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_trabajo', '0001_initial'),
        ('app_PLD', '0002_initial'),
        ('app_personas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_personas.persona'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='pld',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_PLD.pld'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='trabajo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_trabajo.trabajo'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_trabajo.socio'),
        ),
    ]
