# Generated by Django 4.1.6 on 2023-02-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_personas', '0001_initial'),
        ('app_PLD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pld',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_personas.persona'),
        ),
        migrations.AddField(
            model_name='pld',
            name='personaExpuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_PLD.pldexpuesta'),
        ),
    ]
